### ISSUE TITLE
Why are we using HSV and RGB ?

### ISSUE THREAD

**Issue by whitef0x0** [IMacMcGraw/Necromunda#5]
In the colour.js that is part of our Engine() object, we are generating colors from both HSV and RGB, using the functions `eng.ColourFromHSV()` and `eng.ColourFromRGB()`.

I think it would be simpler if we just stuck to one color representation, unless there is a reason for doing so otherwise.

**Comment by IMacMcGraw** [comment]
Hey David,

What I've done may be uncommon in JS, but I still think it's handy.

In C# you can write constructor overloads, which allow you to create instances of the same class using a different set of parameters, which provides a lot of flexibility. This is essentially what I've done, but because function overloading is not possible in JS, I have had to name the two functions differently, rather than simply using different signatures.

In general I prefer HSV because you can make the colour a little brighter, a little warmer, a little more vibrant etc. by tweaking only one value, without doing some mental math and modifying all three RGB values.

**Comment by IMacMcGraw** [comment]
It seems like CSS and HTML are better at recognising RGB, which is why it is useful to be able to create an RGB colour using HSV parameters.

**Comment by whitef0x0** [comment]
If you want to properly do function overloading you can either write your function like this

`function(param1, optionalparam2, optionalparam3)`

or like this

`function(param_object)`

or you can use the `arguments` variable as discussed like this https://javascriptweblog.wordpress.com/2011/01/18/javascripts-arguments-object-and-beyond/.

I think though that the best way would be to use prototypal inheritance and not use overloading or anything similar as right now it is a bit confusing.

I.e. we should bind to our Colour object two methods, one that accepts RGB format to create a Colour and another that accepts HSV to create a colour. Right now it is not entirely obvious that your Colour constructor creates RGB.
